version: "3.9"

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3000"
    environment:
      - SERVICE_NAME=user-service

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3002:3000"
    environment:
      - SERVICE_NAME=product-service

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "3003:3000"
    environment:
      - SERVICE_NAME=cart-service

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3004:3000"
    environment:
      - SERVICE_NAME=order-service

  wallet-service:
    build: ./wallet-service
    container_name: wallet-service
    ports:
      - "3005:3000"
    environment:
      - SERVICE_NAME=wallet-service

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3006:3000"
    environment:
      - SERVICE_NAME=notification-service
